In [1]:
#reshape problem
import numpy
arr = input().strip().split()
#print(result)

array1=numpy.array(arr,int)
reshape_array1=numpy.reshape(array1,(3,3))
print(reshape_array1)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [2]:
#array  input is 1 2 3 4 -8 -10
import numpy

def arrays(arr):
    array1=numpy.array(arr,float)
    reverse_array=array1[::-1]
    return reverse_array

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [7]:
#treanspose x and flatten
import numpy as np

n,m=map(int,input().split())
array=np.array([input().strip().split() for _ in range(n)],int)
print(array.transpose())
print(array.flatten())


2 2
1 3 
4 5
[[1 4]
 [3 5]]
[1 3 4 5]


In [6]:
n,m=map(int,input().split())

2 2


In [8]:
#another method
import numpy as np

n,m=map(int,input().split())
array=np.array([input().strip().split() for _ in range(n)],int)
transposed_array = np.transpose(array)
print(transposed_array)

# Reshape the array to flatten it
flattened_array = array.reshape(-1)
print(flattened_array)

2 2
3 4
5 6
[[3 5]
 [4 6]]
[3 4 5 6]


In [10]:
# to concanetate
import numpy as np

n,m,p=map(int,input().split()) #where n,m,p is n,m :rows,p:column

array1=np.array([input().strip().split() for _ in range(n)],int)
array2=np.array([input().strip().split() for _ in range(m)],int)
conc=np.concatenate((array1,array2),axis=0) #axis=0 (concanetate along  the rows)
                                            #axis=1(concat along columns)
print(conc)


3 2 3
1 2 3
4 5 6
7 8 9
10 11 12
13 14 15
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [13]:
array=map(int, input().split())
print(array)

3 3 3


In [14]:
import numpy 

nums=tuple(map(int, input().split()))

print(numpy.zeros(nums, dtype=numpy.int))
print(numpy.ones(nums, dtype=numpy.int))
#3,3,3=dimension,rows,columns which 3dimension i.e 3x3 matrix



 3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


C:\Users\Admin\AppData\Local\Temp/ipykernel_17128/3854832955.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  print(numpy.zeros(nums, dtype=numpy.int))
C:\Users\Admin\AppData\Local\Temp/ipykernel_17128/3854832955.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the releas

In [16]:
array=np.zeros((3,3,3))
array.shape

(3, 3, 3)

In [17]:
#eye and identity
import numpy
numpy.set_printoptions(legacy='1.13')
array=numpy.eye(*map(int,input().split()))
print(array)

#identity
import numpy
print(numpy.identity(3)) #3 is for  dimension 3 X 3


3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [18]:
#arithmetic 
import numpy

n,m=map(int,input().split())
A=numpy.array([input().split() for _ in range(n)],dtype=int)
B=numpy.array([input().split() for _ in range(n)],dtype=int)
print(A+B,A-B,A*B,A//B,A%B,A**B,sep='\n')




1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [19]:
#floor ciel 
my_array=numpy.array([[1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9]])
print(numpy.floor(my_array) )#[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
print(numpy.ceil(my_array) ) ##[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
print(numpy.rint(my_array) ) ##[  1.   2.   3.   4.   6.   7.   8.   9.  10.]

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]]
[[  2.   3.   4.   5.   6.   7.   8.   9.  10.]]
[[  1.   2.   3.   4.   6.   7.   8.   9.  10.]]


The tool ceil returns the ceiling of the input element-wise.The ceiling of   x is the smallest integer  where .i>x
The rint tool rounds to the nearest integer of input element-wise.


In [23]:
array=map(int,input().split())
print(array)

1 2 3 4


In [27]:
array=numpy.array(input().split(),float)
print(array)

1.1 2.2 3.3
[ 1.1  2.2  3.3]


In [3]:
import numpy #1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
numpy.set_printoptions(legacy='1.13')
array=numpy.array(input().split(),float)
array_floor=numpy.floor(array)
array_ceil=numpy.ceil(array)
array_rint=numpy.rint(array)
print(array_floor,array_ceil,array_rint,sep='\n')





1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [2]:
#sum and prod axis=0-column wise operation axis=1-row wise operation performed
import numpy

n,m=map(int,input().split())
array=numpy.array([input().split() for _ in range(n)],int) #The sum along axis 0 = [4 6 ]
                                                             #The product of this sum = 24
print(numpy.prod(numpy.sum(array,axis=0),axis=None))

2 2
1 2
3 4
24


In [5]:
#min and max
import numpy as np

n,m=map(int,input().split())
array=np.array([input().split() for _ in range(n)],int)
print(np.max(np.min(array,axis=1)))
'''
4 2
3 5
2 7
1 3
4 0'''

4 2
3 5
2 7
1 3
4 0
3


In [9]:
import numpy
my_array = numpy.array([[2, 5], 
                        [3, 7],
                        [1, 3],
                        [4, 0]])

print (numpy.min(my_array, axis = 0))         #Output : [1 0]
print (numpy.min(my_array, axis = 1))         #Output : [2 3 1 0]
print (numpy.min(my_array, axis = None) )     #Output : 0
print (numpy.min(my_array))                   #Output : 0

[1 0]
[2 3 1 0]
0
0


#Task

You are given a 2-D array of size nxm.
Your task is to find:

The mean along axis 1 
The var along axis 0
The std along axis none


In [10]:
#import numpy as np   #2 2 1 2 3 4

n,m=map(int,input().split())
array1=np.array([input().split() for _ in range(n)], int)
print(np.mean(array1,axis=1))
print(np.var(array1,axis=0))
std_array=np.std(array1,axis=None)
print(round(std_array,11))


2 2 
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [11]:
#matrix multiplication #2 1 2 3 4 1 2 3 4
#print numpy.dot(A, B)       #Output : 11
#print numpy.cross(A, B)     #Output : -2
import numpy as np

n=int(input())
A=np.array([input().split() for _ in range(n)],int)
B=np.array([input().split() for _ in range(n)],int)
print(np.matmul(A,B))


2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [12]:
#inner tol
import numpy

A = numpy.array([0, 1])
B = numpy.array([3, 4])

print numpy.inner(A, B)     #Output : 4

SyntaxError: invalid syntax (Temp/ipykernel_11852/2341372396.py, line 7)

In [13]:
import numpy as np #0 1  2 3

A=np.array(input().split() ,int)
B=np.array(input().split() ,int)

print(np.inner(A,B),np.outer(A,B),sep='\n')


0 1 
2 3
3
[[0 0]
 [2 3]]


poly

The poly tool returns the coefficients of a polynomial with the given sequence of roots.

print numpy.poly([-1, 1, 1, 10])        #Output : [  1 -11 9 11 -10] 
polyval:

The polyval tool evaluates the polynomial at specific value.

print numpy.polyval([1, -2, 0, 2], 4)   #Output : 34


In [14]:
#polynomial code #1.1 2 3 0
import numpy

poly_array=list(map(float,input().split()))
value=int(input())

print(numpy.polyval(poly_array,value))



1.1 2 3
0
3.0


In [15]:
#determinat of matrix 2 1.1 1.1 1.1 1.1
import numpy

n=int(input())
A=numpy.array([input().split() for _ in range(n)],float)
print(numpy.linalg.det(A))




2
1.1 1.1
1.1 1.1
0.0
